apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: Opaque
stringData:
  username: admin
  password: Harbor12345
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: ReplaceWithHost/library/hello:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80 # clusterIP port
      targetPort: 8080 # process port
      nodePort: 30080 #external
  type: NodePort
